Fix prefix argument so that it applies consistently even on windows
shuLhan/go-bindata pull request #20
Opened 2017-11-11 23:55 UTC by m-r-hunt

After updating from the old unmaintained jteeuwen version I had issues using the prefix argument:

* Having any prefix argument changes the behaviour significantly (in my case it was using full paths instead of relative paths with any prefix present). It also won't do the fix that is marked for issue #110 in this case.
* The prefix is a regexp now. This is different from the old version and not documented.
* On windows, the prefix regexp is applied to the path with backslashes in. This makes it harder to write code that's consistent across platforms.

Also slightly unrelated but very close in the code: on Windows, a leading slash won't be removed.

Here's a pull request that fixes these problems.

P.S. Thanks for maintaining this fork. I was having problems with the old version due to it not listing "DO NOT EDIT" in the correct place, so golint was confused.

2017-11-12 08:49 UTC, shuLhan commented
This PR break the symlink test on `convert_test.go`.

2017-11-12 09:02 UTC, m-r-hunt commented
Sorry, this test was failing for me before as well (on Windows). I may be able to have a look on Linux and see if I can correct it.

2017-11-17 17:12 UTC, shuLhan requested changes
This PR break the symlink test on convert_test.go.

2020-04-07 13:58 UTC, shuLhan commented
Closing due to no response. Sorry.

2020-04-07 13:58 UTC, closed without merging